# Linear Algebra Review

Linear algebra is a compact way to represent/operate sets of linear equations

In [1]:
# Pass a list of integers as an array
import numpy as np
A=np.array( [ [1,2,3], [4,5,6] ] )

In [2]:
B=np.array([1,2,3])
B.T

array([1, 2, 3])

In [3]:
#b.T shows size of a as num rows, then num columns
B[2]

3

In [4]:
# remember Python starts indices with zero, not 1
A[:,0]

# in Python, you can simply use A[1]
A[1,:]

array([4, 5, 6])

In [5]:
# Hadamard product = elementwise multiplication

# 1st "random" is the package; 2nd "random" is the function
A=np.random.random((2,3))

In [6]:
A.shape[0]

2

## Element-wise multiplication of A & A using two for-loops

In [7]:
C=np.zeros((2,3))

for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        C[i,j]=A[i,j]*A[i,j]

np.sum(np.abs(C-A*A))

0.0

## Matrix multiplication
Python/Numpy uses the @ symbol for matrix multiplication (as opposed to * for element-wise)

In [8]:
A=np.random.random((2,3))
B=np.random.random((3,4))

AB=np.zeros((A.shape[0],B.shape[1]))

for i in range(A.shape[0]):
    for j in range(B.shape[1]):
        for k in range(A.shape[1]):
            
            # += adds another value with the variable's value and assigns the new value to the variable
            #    i.e. >> x = 3
            #         >> x += 2
            #         >> print x
            #       5
            AB[i,j] += A[i,k]*B[k,j]
            
np.sum(np.abs(AB-A@B))

0.0

## Vector-vector products (aka inner/dot product)
...without using @

**CRITICAL** - the @ function falls back to the inner product by default IF matrix dimensions do not allow for a matrix multiplication!!!

In [9]:
A=np.random.random((5,1))
B=np.random.random((5,1))

C=np.zeros((3,))

for n in range(len(A)):
    C += A[n]*B[n]

C

array([1.47680016, 1.47680016, 1.47680016])

## Outer products
For vectors of arbitrary lengths:

column vector * row vector = [x1y1 x1y2 ... x1yN; x2y1 x2y2 ... x2yN; ...; xNy1 ... xNyN]

In [10]:
A=np.random.random((2,1))
B=np.random.random((1,5))

C=np.zeros((2,5))

for i in range(len(A)):
    for j in range(len(B)):
        C[i,j] = A[i,0]*B[0,j]

np.sum(np.abs(C-np.outer(A,B)))

2.511299083851751

In [11]:
# "Broadcasting"
print(np.sum(np.abs(A@B - np.outer(A,B))))

0.0


In [12]:
# a fun trick with outer products
a=[1,2,3]
np.outer(a,[1,1,1])

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

# Matrix-vector products
useful for PCA etc.

In [13]:
# for y = Ax, with A written by rows (i.e. a1 is for 1st row of A)
A=np.random.random((7,3))
x=np.random.random((3,1))
y=np.zeros((7,1))

for i in range(A.shape[0]):
    y[i] = A[i] @ x

print( np.sum(np.abs(y-A@x)) )

0.0


In [27]:
# if A were defined column-wise (i.e. a1 is for the first COLUMN of A)
# this version makes it more obvious that y is a linear combination
A=np.random.random((7,3))

# broadcast variables automatically "fill in" non-matching variables so that matrix sizes are appropriate.
# Over-defining the vector, for this example, actually caused the operation inside the for-loop to
# become a matrix (not element) multiplication, causing the code to fail. To prevent this, the
# below variables' 2nd dimensions were purposely left undefined.
x=np.random.random((3,))
y=np.zeros((7,))

for i in range(A.shape[1]):
    y += A[:,i] * x[i,0]
    
print( np.sum(np.abs(y-A@x)) )

0.0


In [25]:
A[:,i].shape

(7,)

## Identity matrix

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Diagonal matrix

In [16]:
np.diag([5,4,3,2,1])

array([[5, 0, 0, 0, 0],
       [0, 4, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 1]])

## Transpose of a matrix

In [18]:
T=np.repeat([[1,2,3]], repeats=5, axis=0)

print(T)
print('  ')
print(T.T)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
  
[[1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]]


## Symmetric matrix
Matrix is equal to its own transpose; **anti-** symmetric if matrix is negative version of that

## Trace of a matrix
Sum of elements of diagonal